CREATE TABLE "ResearchPlan" ("id" TEXT NOT NULL, "organisationId" TEXT, "publicationId" TEXT NOT NULL, "publicationVersionId" TEXT NOT NULL, "taxonomyVersion" TEXT NOT NULL, "jurisdictions" TEXT[], "questions" TEXT[], "passagesJson" JSONB NOT NULL, "unresolvedQuestions" TEXT[], "status" TEXT NOT NULL DEFAULT 'REVIEW_REQUIRED', "createdById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ResearchPlan_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ResearchPlan_publicationId_publicationVersionId_idx" ON "ResearchPlan"("publicationId", "publicationVersionId");
CREATE INDEX "ResearchPlan_organisationId_status_idx" ON "ResearchPlan"("organisationId", "status");
CREATE TABLE "PublicationReviewComment" ("id" TEXT NOT NULL, "reviewItemId" TEXT NOT NULL, "targetId" TEXT NOT NULL, "body" TEXT NOT NULL, "actorId" TEXT, "actorName" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "PublicationReviewComment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PublicationReviewComment_reviewItemId_status_idx" ON "PublicationReviewComment"("reviewItemId", "status");
CREATE TABLE "PublicationReviewLock" ("id" TEXT NOT NULL, "reviewItemId" TEXT NOT NULL, "revision" INTEGER NOT NULL DEFAULT 1, "lockedById" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PublicationReviewLock_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PublicationReviewLock_reviewItemId_key" ON "PublicationReviewLock"("reviewItemId");
CREATE TABLE "BriefRevision" ("id" TEXT NOT NULL, "publicationId" TEXT NOT NULL, "publicationVersionId" TEXT NOT NULL, "contentMarkdown" TEXT NOT NULL, "changesJson" JSONB NOT NULL, "evidenceRefs" TEXT[], "status" TEXT NOT NULL DEFAULT 'REVIEW_REQUIRED', "reviewerId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedAt" TIMESTAMP(3), CONSTRAINT "BriefRevision_pkey" PRIMARY KEY ("id"));
CREATE INDEX "BriefRevision_publicationId_createdAt_idx" ON "BriefRevision"("publicationId", "createdAt");
